[package]
name = "oxidai_cli_client"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
reqwest = { version = "0.12.5", features = ["blocking"] }
tokio = { version = "1.39.2", features = ["full"] }

[dev-dependencies]
anyhow = "1.0.86"
